# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  test:
    docker:
      - image: cimg/node:18.1.0
      - image: cimg/postgres:14.0
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: test
            POSTGRES_PASSWORD: 1234

    steps:
      - checkout

      - node/install-packages:
          pkg-manager: npm
      - setup_remote_docker:
          version: 20.10.14

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Run tests
          command: npm test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths: .

  deploy:
    docker:
      - image: cimg/node:18.1.0
    steps:
    - attach_workspace:
          at: .

    - run: npm install typescript -g
    - run:
        name: Build
        command: tsc
      
    - run:
        name: Authenticate with registry
        command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
    - run:
        name: Publish package
        command: npm publish

workflows:
  sample:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
      - deploy:
          context:
            - main
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
