name: versioning

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  versioning:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}
      - name: 'cat package.json'
        run: cat ./package.json
      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'v'
          minor-wording:  'add,Adds,new'
          major-wording:  'MAJOR,cut-major,major'
          patch-wording:  'patch,fix,fixes'
          rc-wording:     'RELEASE,alpha'
#           skip-tag: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}


      
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18.1.0
      - run: npm install
#      - run: npm test
#      - uses: JS-DevTools/npm-publish@v1
#        with:
#          token: ${{ secrets.MY_NPM_TOKEN }}

      - run: npm i typescript -g
      - run: tsc
      - run: rm .gitignore
      - run: ls

      - name: 'cat package.json'
        run: cat ./package.json
      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
